#!/bin/bash

WORK_DIR=work/

PROJECT_HOME=$(dirname $(readlink -f $0))
cd $PROJECT_HOME || exit 1

export updated=0
export updated14=0
export updated15=0
export version=""
export force=0

if [ "$1" == "force" ];
then
	force=1
fi

function on_exit()
{
	echo "-- END $(date)"
}
trap on_exit EXIT

echo
echo "-- START $(date)"
echo "PROJECT_HOME = $PROJECT_HOME"

echo "Preparing work directories..."
mkdir -p $WORK_DIR || exit 1
mkdir -p $WORK_DIR/haproxy || exit 1
mkdir -p $WORK_DIR/haproxy-dconv || exit 1


echo "Fetching HAProxy 1.4 repository..."
if [ ! -e $WORK_DIR/haproxy/1.4 ];
then
	git clone -v http://git.1wt.eu/git/haproxy-1.4.git/ $WORK_DIR/haproxy/1.4 || exit 1
fi
cd $WORK_DIR/haproxy/1.4 || exit 1
	OLD_MD5=$(md5sum doc/configuration.txt)
	git checkout master && git pull -v
	haproxy14_git_version=$(git describe --tags --match 'v*')
	haproxy14_git_version=${haproxy14_git_version%-g*}
	NEW_MD5=$(md5sum doc/configuration.txt)
	if [ "$OLD_MD5" != "$NEW_MD5" ];
	then
		updated14=1
	fi
cd $PROJECT_HOME

echo "Fetching HAProxy 1.5 repository..."
if [ ! -e $WORK_DIR/haproxy/1.5 ];
then
	git clone -v http://git.1wt.eu/git/haproxy.git/ $WORK_DIR/haproxy/1.5 || exit 1
fi
cd $WORK_DIR/haproxy/1.5 || exit 1
	OLD_MD5=$(md5sum doc/configuration.txt)
	git checkout master && git pull -v
	haproxy15_git_version=$(git describe --tags --match 'v*')
	haproxy15_git_version=${haproxy15_git_version%-g*}
	NEW_MD5=$(md5sum doc/configuration.txt)
	if [ "$OLD_MD5" != "$NEW_MD5" ];
	then
		updated15=1
	fi
cd $PROJECT_HOME

echo "Fetching last haproxy-dconv public version..."
if [ ! -e $WORK_DIR/haproxy-dconv/master ];
then
	git clone -v git://github.com/cbonte/haproxy-dconv.git $WORK_DIR/haproxy-dconv/master || exit 1
fi
cd $WORK_DIR/haproxy-dconv/master || exit 1
	OLD_MD5="$(git log -1 | md5sum) $(git describe --tags)"
	git checkout master && git pull -v
	version=$(git describe --tags)
	version=${version%-g*}
	NEW_MD5="$(git log -1 | md5sum) $(git describe --tags)"
	if [ "$OLD_MD5" != "$NEW_MD5" ];
	then
		export updated=1
	fi
cd $PROJECT_HOME

echo "Fetching last haproxy-dconv public pages version..."
if [ ! -e $WORK_DIR/haproxy-dconv/gh-pages ];
then
	git clone -v -b gh-pages git@github.com:cbonte/haproxy-dconv.git $WORK_DIR/haproxy-dconv/gh-pages || exit 1
fi
cd $WORK_DIR/haproxy-dconv/gh-pages || exit 1
	git checkout gh-pages && git pull -v
cd $PROJECT_HOME

if [ "$force" == 1 -o "$updated" == "1" -o "$updated14" == "1" ];
then
	echo "Generating documentation for HAProxy 1.4..."
	cd $WORK_DIR/haproxy-dconv/master || exit 1
		./haproxy-dconv.py -i ../../haproxy/1.4/doc/configuration.txt -o ../gh-pages/configuration-1.4.html &&
		sed -i "s/\(<\!-- VERSION-1\.4 -->\)\(.*\)\(<\!-- \/VERSION-1\.4 -->\)/\1${haproxy14_git_version}\3/" ../gh-pages/index.html
	cd $PROJECT_HOME
fi

if [ "$force" == 1 -o "$updated" == "1" -o "$updated15" == "1" ];
then
	echo "Generating documentation for HAProxy 1.5..."
	cd $WORK_DIR/haproxy-dconv/master || exit 1
		./haproxy-dconv.py -i ../../haproxy/1.5/doc/configuration.txt -o ../gh-pages/configuration-1.5.html &&
		sed -i "s/\(<\!-- VERSION-1\.5 -->\)\(.*\)\(<\!-- \/VERSION-1\.5 -->\)/\1${haproxy15_git_version}\3/" ../gh-pages/index.html
	cd $PROJECT_HOME
fi

echo "- haproxy-1.4 version : $haproxy14_git_version"
echo "- haproxy-1.5 version : $haproxy15_git_version"
echo "- haproxy-dconv version : $version"

echo "Synchronize generated documentations..."
cd $WORK_DIR/haproxy-dconv/gh-pages || exit 1
	push=0

	rsync -av --delete ../master/js/ js/ &&
		if [ "$(git status -s js/)" != "" ];
		then
			git commit -m "Updating jquery from haproxy-dconv $version" js/ && push=1
		fi &&
	rsync -av --delete ../master/css/ css/ &&
		if [ "$(git status -s css/)" != "" ];
		then
			git commit -m "Updating custom Bootstrap style from haproxy-dconv $version" css/ && push=1
		fi &&
	if [ "$(git status -s configuration-1.4.html)" != "" ];
	then
		git commit -m "Updating HAProxy documentation ${haproxy14_git_version} generated by haproxy-dconv $version" configuration-1.4.html && push=1
	fi &&
	if [ "$(git status -s configuration-1.5.html)" != "" ];
	then
		git commit -m "Updating HAProxy documentation ${haproxy15_git_version} generated by haproxy-dconv $version" configuration-1.5.html && push=1
	fi &&
	if [ "$(git status -s)" != "" ];
	then
		git commit -a -m "Generated documentations based on haproxy-dconv $version" && push=1
	fi &&
	if [ "$push" == "1" ];
	then
		git push origin gh-pages
	fi
